services:
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3555:80"

  backend:
    restart: always
    image: node:18-alpine
    command: ["npm","run", "dev", "--prefix", "/app"]
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app

  frontend:
   image: node:18-alpine
   restart: always
#   command: ["npm","run", "dev", "--prefix", "/app"]
   build:
     context: ./frontend
     dockerfile: dev.dockerfile
   ports:
    - "3001:3001"
   volumes:
     - ./frontend/src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
