version: '3.8'

services:
  nginx:
    restart: always
    depends_on:
#      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3555:80"

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_URI=mongodb://root:password@mongo:27017

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile

  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  db_data:
