name: Checks

on: [push, pull_request]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i --prefix ./backend
    - name: Run ESLint
      run: npm run eslint . --fix --prefix ./backend
    - name: Build typescript
      run: npm run build --prefix ./backend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm ci --prefix ./frontend
    - name: Run ESLint
      run: npm run lint --prefix ./frontend
    - name: Build typescript
      run: npm run build --prefix ./frontend
