name: Eslint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i --prefix ./backend
    - name: Run ESLint
      run: npm run eslint . --ext .js,.jsx,.ts,.tsx --fix --prefix ./backend