on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: create env files
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > ./frontend/.env;
          echo "${{ secrets.BACKEND_ENV }}" > ./backend/.env;

      - name: compose build
        run: docker compose build

      - name: compose up
        run: docker compose up -d
